services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "metrics"
      POSTGRES_USER: "postgres"
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "admin"
      REQUIRE_CAPTCHA: false

    ports:
      - "25565:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "cb" ]
      interval: 2s
      timeout: 2s
    restart: unless-stopped
