{
 "title": "Analytical hackaton",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Распределение вопросов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Распределение вопросов к ИИ по категориям",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  category,\r\n  COUNT(*) AS count\r\nFROM\r\n  public.answers\r\nGROUP BY\r\n  category\r\nORDER BY\r\n  count DESC\r\n"
    }
   ]
  },
  {
   "title": "Качество ответов по каждой из категорий",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  category,\r\n  AVG(score) AS avg_score\r\nFROM\r\n  public.answers\r\nWHERE\r\n  score IS NOT NULL\r\n  AND category IS NOT NULL\r\nGROUP BY\r\n  category\r\nORDER BY\r\n  avg_score DESC\r\n"
    }
   ]
  },
  { "title": "Оценки", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Описание метрики",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "options": {
    "content": "Расчет `score` на основе оценок пользователей\n\nлюбой пользователь может поставть\nлайк и дизлайк на ответ модели\n\n- like - 1\n- dislike - 0\n\nметрика считает среднее значение и выводит его"
   }
  },
  {
   "title": "Качество ответов ИИ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  AVG(score) AS avg_score\r\nFROM\r\n  public.answers\r\n"
    }
   ]
  },
  {
   "title": "Перцентили качество ответов",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  percentile_cont(0.50) WITHIN GROUP (ORDER BY score) AS p50,\r\n  percentile_cont(0.75) WITHIN GROUP (ORDER BY score) AS p75,\r\n  percentile_cont(0.95) WITHIN GROUP (ORDER BY score) AS p95\r\nFROM\r\n  public.answers\r\n"
    }
   ]
  },
  { "title": "Запросы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Количество ответов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS total_answers\r\nFROM\r\n  public.answers\r\n"
    }
   ]
  },
  {
   "title": "Запросы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('day', tmiestamp) AS day,\r\n  COUNT(*) AS total_requests\r\nFROM\r\n  public.answers\r\nGROUP BY\r\n  day\r\nORDER BY\r\n  day\r\n"
    }
   ]
  }
 ]
}